AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: p3.2xlarge
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: keyname
      ImageId: 'ami-0484cefb8f48dafe8'
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: myipaddr
Outputs:
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]